language: cpp
compiler: gcc
notifications:
  email: false
  
script:  # run the main program first then run tests
- make && ./a.out
- cd _TEST
- sh configure.sh
- g++ -Wall -std=c++11 TEST-cases.cc -o run_tests
- ./run_tests
- cd ..